### ISSUE TITLE
Extension is incompatible with dark theme

### ISSUE THREAD

**Issue by kenzo44** [Fraser-Greenlee/show-tabs#1]
The borders are hidden when Brackets is being used in a dark theme.

**Comment by Fraser-Greenlee** [comment]
Just posted a fix, thanks for posting the issue.

**Comment by fluxxus** [comment]
@Fraser-Greenlee Totally unrelated to the extension, but didn't knew where to ask.

Could you please tell me what theme and font are you using in the screenshots?

Thanks
